arb-dir: lib\src\localization
template-arb-file: app_ar.arb
output-dir: lib/src/common/generated
output-localization-file: app_localizations.dart
synthetic-package: false
nullable-getter: false
untranslated-messages-file: untranslated_messages.json